Remove logging of upgrade to TLS
ruffrey/smtpd pull request #8
Opened 2022-07-06 14:01 UTC by mjmayer

Logging of upgrade to TLS muddies the logs and doesn't add much value.

2022-07-06 20:36 UTC, ruffrey commented
Feedback from call - make this behind the verbose config property 

> On Jul 6, 2022, at 7:01 AM, Michael Mayer ***@***.***> wrote:
> 
> ﻿
> Logging of upgrade to TLS muddies the logs and doesn't add much value.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/mailsac/smtpd/pull/8
> 
> Commit Summary
> 
> 0faefbf Remove logging of upgrade to TLS
> File Changes  (1 file)
> M server.go (3)
> Patch Links:
> 
> https://github.com/mailsac/smtpd/pull/8.patch
> https://github.com/mailsac/smtpd/pull/8.diff
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because your review was requested.

2022-07-07 14:42 UTC, mjmayer commented
I've put the "TLS Upgraded" error message behind the server's verbose flag.

2022-07-21 21:58 UTC, ruffrey requested changes

2022-07-21 21:58 UTC, ruffrey commented on server.go
> +				if conn.server.Verbose {
This is not a message ID, it is the pre-TLS connection ID.

2022-07-28 15:27 UTC, ruffrey approved these changes

2022-07-28 17:22 UTC, merged